### ISSUE TITLE
Crash on Samsung device with API19 related to `android:elevation` returning invalid value

### ISSUE THREAD

**Issue by plnice** [airbnb/paris#73]
To reproduce:
1. Checkout https://github.com/plnice/epoxy-paris-talk
1. Run the app on Samsung device with 4.4 (emulator works fine, Samsung device I've used for tests: SM-G357FZ, Android 4.4.4)

```
Error	09:38:28.792	14817	14817	AndroidRuntime	FATAL EXCEPTION: main
Process: com.github.plnice.epoxyparistalk, PID: 14817
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.plnice.epoxyparistalk/com.github.plnice.epoxyparistalk.main.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class com.github.plnice.epoxyparistalk.main.view.ListItemParisCustomView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2370)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5426)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.github.plnice.epoxyparistalk.main.view.ListItemParisCustomView
	at android.view.LayoutInflater.createView(LayoutInflater.java:627)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:703)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.github.plnice.epoxyparistalk.main.view.MainActivityView.onCreate(MainActivityView.kt:19)
	at com.github.plnice.epoxyparistalk.main.MainActivity.onCreate(MainActivity.kt:19)
	at android.app.Activity.performCreate(Activity.java:5296)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:601)
	... 22 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:465)
	at com.airbnb.paris.typed_array_wrappers.TypedArrayTypedArrayWrapper.getDimensionPixelSize(TypedArrayTypedArrayWrapper.kt:35)
	at android.view.ViewStyleApplier.processAttributes(ViewStyleApplier.java:93)
	at com.airbnb.paris.StyleApplier.apply(StyleApplier.kt:60)
	at android.widget.TextViewStyleApplier.applyParent(TextViewStyleApplier.java:38)
	at com.airbnb.paris.StyleApplier.apply(StyleApplier.kt:47)
	at com.github.plnice.epoxyparistalk.main.view.ListItemParisCustomViewStyleApplier.processStyleableFields(ListItemParisCustomViewStyleApplier.java:42)
	at com.airbnb.paris.StyleApplier.apply(StyleApplier.kt:54)
	at com.airbnb.paris.StyleApplier.apply(StyleApplier.kt:35)
	at com.github.plnice.epoxyparistalk.main.view.ListItemParisCustomView.<init>(ListItemParisCustomView.kt:47)
	at com.github.plnice.epoxyparistalk.main.view.ListItemParisCustomView.<init>(ListItemParisCustomView.kt:21)
	at com.github.plnice.epoxyparistalk.main.view.ListItemParisCustomView.<init>(ListItemParisCustomView.kt)
	... 25 more
```

**Comment by kristiyanP** [comment]
This is a tricky issue! 

I believe the best course of action is to forward the UnsupportedOperationException to the view handling the attribute, so that it can be caught and dealt with.

The exception may be useful when you need handle the attribute to ensure a certain type of layout.

**Comment by ngsilverman** [comment]
@plnice oh good point, I wasn't even thinking of the support library. I agree with your assessment, option 1 seems like the way to go.
